name: Release

on: 
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        emulator: ["pubsub"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: google-github-actions/release-please-action@master
        id: release
        with:
          release-type: node
          package-name: ${{ matrix.emulator }}
          monorepo-tags: true
          path: emulators/${{ matrix.emulator }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
        if: ${{ steps.release.outputs.release_created }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            kmarilleau/gce-${{ matrix.emulator }}:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
            kmarilleau/gce-${{ matrix.emulator }}:latest"
        if: ${{ steps.release.outputs.release_created }}
